spring.datasource.url=jdbc:postgresql://212.67.12.82:5432/your_database_name
spring.datasource.username=pg-simultex
spring.datasource.password=simultexPG123+
spring.datasource.driver-class-name=org.postgresql.Driver

testing.app.secret=43uoefjrwalkmdc1
testing.app.lifetime=60000

spring.jpa.open-in-view=false
